# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-06 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='nickname',
            field=models.CharField(default='bob', max_length=30),
        ),
    ]
